window.DEFAULT_ACADEMIC_SCHEDULE = [
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-01",
    "dayType": "공휴일",
    "title": "3.1절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-03",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-04",
    "dayType": "해당없음",
    "title": "개학식",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-08",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-15",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-19",
    "dayType": "해당없음",
    "title": "학부모 총회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-22",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-26",
    "dayType": "해당없음",
    "title": "전국연합학력평가",
    "content": "보통과 1,2,3학년 진행",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-03-29",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-01",
    "dayType": "휴업일",
    "title": "개교기념일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-05",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-07",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "경기도지방기능경기대회",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-08",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "경기도지방기능경기대회",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-09",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "경기도지방기능경기대회",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-09",
    "dayType": "해당없음",
    "title": "재난대피훈련 및 자체 소방훈련",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-10",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "경기도지방기능경기대회",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-11",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "경기도지방기능경기대회",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-12",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-19",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-26",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-04-30",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-01",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-02",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-03",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-05",
    "dayType": "공휴일",
    "title": "석가탄신일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-05",
    "dayType": "공휴일",
    "title": "어린이날",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-06",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-08",
    "dayType": "해당없음",
    "title": "3학년 모의고사",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-10",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-15",
    "dayType": "해당없음",
    "title": "진로콘서트",
    "content": "진로진학컨설팅",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-17",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-23",
    "dayType": "해당없음",
    "title": "현장체험학습",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-24",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-27",
    "dayType": "해당없음",
    "title": "건강검진",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-28",
    "dayType": "해당없음",
    "title": "건강검진",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-29",
    "dayType": "해당없음",
    "title": "결핵검사",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-30",
    "dayType": "해당없음",
    "title": "결핵검사",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-05-31",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-06-03",
    "dayType": "공휴일",
    "title": "대통령선거일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-06-04",
    "dayType": "해당없음",
    "title": "전국연합학력평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-06-07",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-06-14",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-06-21",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-06-23",
    "dayType": "해당없음",
    "title": "학생회장선거",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-06-28",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-01",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-02",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-03",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-04",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-05",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-08",
    "dayType": "해당없음",
    "title": "직업기초능력평가",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-08",
    "dayType": "해당없음",
    "title": "학교자율교육과정운영주간",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-09",
    "dayType": "해당없음",
    "title": "직업기초능력평가",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-09",
    "dayType": "해당없음",
    "title": "학교자율교육과정운영주간",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-10",
    "dayType": "해당없음",
    "title": "직업기초능력평가",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-10",
    "dayType": "해당없음",
    "title": "학교자율교육과정운영주간",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-11",
    "dayType": "해당없음",
    "title": "직업기초능력평가",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-11",
    "dayType": "해당없음",
    "title": "학교자율교육과정운영주간",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-12",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-14",
    "dayType": "해당없음",
    "title": "SLAT-A",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-19",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-21",
    "dayType": "해당없음",
    "title": "여름방학식",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-22",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-23",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-24",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-25",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-26",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-28",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-29",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-30",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-07-31",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-01",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-02",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-04",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-05",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-06",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-07",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-08",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-09",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-11",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-12",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-13",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-14",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-15",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-18",
    "dayType": "해당없음",
    "title": "여름방학개학식",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-23",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-08-30",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-03",
    "dayType": "해당없음",
    "title": "전국연합학력평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-06",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-10",
    "dayType": "해당없음",
    "title": "재난대피훈련 및 자체 소방훈련",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-13",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-19",
    "dayType": "해당없음",
    "title": "복하제",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-20",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-22",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-23",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-24",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-25",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-26",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-27",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-09-30",
    "dayType": "해당없음",
    "title": "체육한마당",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-03",
    "dayType": "공휴일",
    "title": "개천절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-04",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-06",
    "dayType": "공휴일",
    "title": "추석",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-07",
    "dayType": "공휴일",
    "title": "추석연휴",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-08",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-09",
    "dayType": "공휴일",
    "title": "한글날",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-10",
    "dayType": "휴업일",
    "title": "재량휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-11",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-14",
    "dayType": "해당없음",
    "title": "전국연합학력평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-17",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-18",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-20",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-21",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-25",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-10-30",
    "dayType": "해당없음",
    "title": "진로콘서트",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-01",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-08",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-13",
    "dayType": "휴업일",
    "title": "대학수학능력시험",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-14",
    "dayType": "휴업일",
    "title": "재량휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-15",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-19",
    "dayType": "해당없음",
    "title": "수학여행",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-20",
    "dayType": "해당없음",
    "title": "수학여행",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-21",
    "dayType": "해당없음",
    "title": "수학여행",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-22",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-11-29",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-06",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-13",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-16",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-17",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-18",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-19",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-20",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-25",
    "dayType": "공휴일",
    "title": "성탄절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-27",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-29",
    "dayType": "해당없음",
    "title": "학교자율교육과정운영주간",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-30",
    "dayType": "해당없음",
    "title": "학교자율교육과정운영주간",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2025-12-31",
    "dayType": "해당없음",
    "title": "학교자율교육과정운영주간",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-01",
    "dayType": "공휴일",
    "title": "신정",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-03",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-09",
    "dayType": "해당없음",
    "title": "졸업식",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-09",
    "dayType": "해당없음",
    "title": "종업식",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-10",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-12",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-13",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-14",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-15",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-16",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-17",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-17",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-18",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-19",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-20",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-21",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-22",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-23",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-24",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-24",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-25",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-26",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-27",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-28",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-29",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-30",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-31",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-01-31",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-01",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-02",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-03",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-04",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-05",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-06",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-07",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-07",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-08",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-09",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-10",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-11",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-12",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-13",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-14",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-14",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-15",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-16",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-17",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-18",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-19",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-20",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-21",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-21",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-22",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-23",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-24",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-25",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-26",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-26",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-27",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-02-28",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-01",
    "dayType": "공휴일",
    "title": "3·1절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-02",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-03",
    "dayType": "해당없음",
    "title": "입학식",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-03",
    "dayType": "해당없음",
    "title": "개학식",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-07",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-14",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-18",
    "dayType": "해당없음",
    "title": "학부모 총회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-21",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-24",
    "dayType": "해당없음",
    "title": "전국연합학력평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-03-28",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-04",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-06",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-07",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-08",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-09",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-10",
    "dayType": "해당없음",
    "title": "지방기능대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-11",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-18",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-25",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-28",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-29",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-04-30",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-01",
    "dayType": "공휴일",
    "title": "노동절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-02",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-04",
    "dayType": "휴업일",
    "title": "개교기념일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-05",
    "dayType": "공휴일",
    "title": "어린이날",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-07",
    "dayType": "해당없음",
    "title": "3학년 전국연합평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-09",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-14",
    "dayType": "해당없음",
    "title": "교외체험학습활동",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-15",
    "dayType": "해당없음",
    "title": "체육한마당",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-16",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-20",
    "dayType": "해당없음",
    "title": "경기도영농학생축제",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-21",
    "dayType": "해당없음",
    "title": "경기도영농학생축제",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-23",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-24",
    "dayType": "공휴일",
    "title": "석가탄신일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-25",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-27",
    "dayType": "해당없음",
    "title": "건강검진",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-28",
    "dayType": "해당없음",
    "title": "건강검진",
    "content": "",
    "grade1": true,
    "grade2": false,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-05-30",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-03",
    "dayType": "공휴일",
    "title": "지방선거",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-04",
    "dayType": "해당없음",
    "title": "3학년 수능모의평가",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-04",
    "dayType": "해당없음",
    "title": "전국연합학력평가(고1,2)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-06",
    "dayType": "공휴일",
    "title": "현충일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-06",
    "dayType": "공휴일",
    "title": "현충일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-13",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-15",
    "dayType": "해당없음",
    "title": "필기면제검정(특성화)",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-16",
    "dayType": "해당없음",
    "title": "필기면제검정(특성화)",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-17",
    "dayType": "해당없음",
    "title": "필기면제검정(특성화)",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-18",
    "dayType": "해당없음",
    "title": "필기면제검정(특성화)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-19",
    "dayType": "해당없음",
    "title": "필기면제검정(특성화)",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-20",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-27",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-06-30",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-01",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-02",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-03",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-04",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-08",
    "dayType": "해당없음",
    "title": "직업기초능력평가",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-09",
    "dayType": "해당없음",
    "title": "직업기초능력평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-10",
    "dayType": "해당없음",
    "title": "직업기초능력평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-11",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-17",
    "dayType": "공휴일",
    "title": "제헌절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-18",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-21",
    "dayType": "해당없음",
    "title": "여름방학식",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-22",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-23",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-24",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-25",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-25",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-26",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-27",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-28",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-29",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-30",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-07-31",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-01",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-01",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-02",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-03",
    "dayType": "휴업일",
    "title": "여름방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-04",
    "dayType": "해당없음",
    "title": "개학식",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-08",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-15",
    "dayType": "공휴일",
    "title": "광복절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2025",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-16",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-17",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-22",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-24",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-25",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-26",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-27",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-28",
    "dayType": "해당없음",
    "title": "전국기능경기대회",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-08-29",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-05",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-12",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-15",
    "dayType": "해당없음",
    "title": "전국영농학생축제",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-16",
    "dayType": "해당없음",
    "title": "전국영농학생축제",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-17",
    "dayType": "해당없음",
    "title": "전국영농학생축제",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-19",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-24",
    "dayType": "공휴일",
    "title": "추석",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-25",
    "dayType": "공휴일",
    "title": "추석",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-26",
    "dayType": "공휴일",
    "title": "추석",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-28",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-29",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-09-30",
    "dayType": "해당없음",
    "title": "1차 정기시험(1,2,3학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-03",
    "dayType": "공휴일",
    "title": "개천절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-05",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-09",
    "dayType": "공휴일",
    "title": "한글날",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-10",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-17",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-20",
    "dayType": "해당없음",
    "title": "전국연합학력평가",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-24",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-10-31",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-07",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-11",
    "dayType": "해당없음",
    "title": "숙박형 체험학습",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-12",
    "dayType": "해당없음",
    "title": "숙박형 체험학습",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-13",
    "dayType": "해당없음",
    "title": "숙박형 체험학습",
    "content": "",
    "grade1": false,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-14",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-19",
    "dayType": "휴업일",
    "title": "대학수학능력시험",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-20",
    "dayType": "휴업일",
    "title": "재량휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-21",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-28",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-11-30",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-01",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-02",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-03",
    "dayType": "해당없음",
    "title": "2차 정기시험(1,2학년)",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-05",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-12",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-19",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-24",
    "dayType": "해당없음",
    "title": "졸업식",
    "content": "",
    "grade1": false,
    "grade2": false,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-24",
    "dayType": "해당없음",
    "title": "종업식",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": false
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-25",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-25",
    "dayType": "공휴일",
    "title": "성탄절",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-26",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-26",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-27",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-28",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-29",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-30",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2026-12-31",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-01",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-01",
    "dayType": "공휴일",
    "title": "신정",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-02",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-02",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-03",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-04",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-05",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-06",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-07",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-08",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-09",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-09",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-10",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-11",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-12",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-13",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-14",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-15",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-16",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-16",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-17",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-18",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-19",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-20",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-21",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-23",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-23",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-24",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-25",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-26",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-27",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-28",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-29",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-30",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-30",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-01-31",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-01",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-02",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-03",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-04",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-05",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-06",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-06",
    "dayType": "공휴일",
    "title": "설날",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-07",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-07",
    "dayType": "공휴일",
    "title": "설날",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-08",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-08",
    "dayType": "공휴일",
    "title": "설날",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-09",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-09",
    "dayType": "공휴일",
    "title": "대체공휴일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-10",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-11",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-12",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-13",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-13",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-14",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-15",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-16",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-17",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-18",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-19",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-20",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-20",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-21",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-22",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-22",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-23",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-24",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-25",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-27",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-27",
    "dayType": "휴업일",
    "title": "토요휴업일",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  },
  {
    "schoolYear": "2026",
    "schoolName": "이천제일고등학교",
    "date": "2027-02-28",
    "dayType": "휴업일",
    "title": "겨울방학",
    "content": "",
    "grade1": true,
    "grade2": true,
    "grade3": true
  }
];
